version: 0.0
os: ubuntu
files:
  - source: /
    destination: ./calendar-app
    overwrite: yes
hooks:
  BeforeInstall:
    - location: calendar-app/build.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root