name: Mirroring and Deploy

on:
  push:
    branches:
      - deploy  # 'deploy'ブランチへのプッシュをトリガー

jobs:
  to_codecommit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ssh://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/aibos-calender
          ssh_private_key: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
          ssh_username: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }}

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: to_codecommit  # `to_codecommit`ジョブが成功した後に実行

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ./calendar-app 
            docker build -t aibos_calender .  # Dockerイメージをビルド
            docker run -p 5000:5000 aibos_calender  # コンテナを実行
